on: [pull_request]
name: Auto-Merge Bot
jobs:
  auto_merge_bot:
    runs-on: ubuntu-latest
    name: EIP Auto-Merge Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run .travis.yml build script
        id: travis
        uses: ktomk/run-travis-yml@v1
        with:
          file: .travis.yml
          steps: |
            before_install
            script
          allow-failure: false
      - name: test results
        run: echo "${{steps.travis.outputs.test-result}} ${{steps.travis.outputs.outcome}} ${{steps.travis.outputs.conclusion}}"
      - name: auto-merge-bot
        uses: alita-moore/EIP-Bot@a1eb27be4f4e580fd96c5ee650d6fd61c95d1d2d # tag 1.1.1
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
