on: [pull_request_target, pull_request_review]
name: Auto-Merge Bot
jobs:
  await_ci:
    runs-on: ubuntu-latest
    name: Await Travis CI Success
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: await-ci
        uses: alita-moore/EIP-Bot@372a671f9eb63df50b1659ccfbe94594c7bbfc29
        id: await-ci
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
  auto_merge_bot:
    runs-on: ubuntu-latest
    needs: [await_ci]
    name: EIP Auto-Merge Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Re-run pull_request_target bot run on pull_request_review
        if: ${{ github.event_name == 'pull_request_review' }}
        uses: alita-moore/EIP-Bot@43acce04e1d1b1e1b30b1a499095daa1da8fec7c
        id: rerun-pull-request-target-on-review
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
      - name: auto-merge-bot
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: alita-moore/EIP-Bot@bbc378a87486973e55d7073b09e0d8e6088326b4
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
